[package]
name = "diecast-scss"
version = "0.1.0"
authors = ["Jorge Israel Peña <jorge.israel.p@gmail.com>"]

[dependencies.sass-rs]
path = "../../sass-rs"

[dependencies.diecast]
path = "../diecast"
